Document: attackfeed-1.0
Title: Debian attackfeed-1.0 Manual
Author: <insert document author here>
Abstract: This manual describes what attackfeed-1.0 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/attackfeed-1.0/attackfeed-1.0.sgml.gz

Format: postscript
Files: /usr/share/doc/attackfeed-1.0/attackfeed-1.0.ps.gz

Format: text
Files: /usr/share/doc/attackfeed-1.0/attackfeed-1.0.text.gz

Format: HTML
Index: /usr/share/doc/attackfeed-1.0/html/index.html
Files: /usr/share/doc/attackfeed-1.0/html/*.html
